# Generated by Django 4.2 on 2023-04-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pet', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=14)),
                ('dia_reserva', models.DateField()),
                ('observacao', models.TextField(blank=True)),
            ],
        ),
    ]
